name: build-api

on:
  push:
    branches:
      - "main"
    paths:
      - 'DockerCourseApi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Spin up database
        run: docker compose up --detach database
      -
        name: Seed database
        run: |
          chmod +x ./Database/wait-and-run.sh
          docker compose run --build database-seed
      -
        name: Build
        run: |
          docker build \
            --tag ${{ vars.DOCKERHUB_USERNAME }}/docker-course-api:latest \
            --tag ${{ vars.DOCKERHUB_USERNAME }}/docker-course-api:${{ github.run_number }} \
            --file ./DockerCourseApi/Dockerfile \
            .
      -
        name: Push
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/docker-course-api:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/docker-course-api:${{ github.run_number }}
      -
        name: Tear down database
        if: always()
        run: docker compose down database
